name: CI workflow  #Name that will be dispalyed on the Action tab

on:  #tag to add events
  push:  #this will trigger the workflow
    branches: ["main"]  #this starts the workflow everytime somebody pushes to the main branch
  pull_request:  #This will also trigger the workflow
    branches: ["main"]  #This starts the workflow everytime someone makes a PR on main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      name: Checkout
      uses: actions/checkout@v3

      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      name: Lint with flake
      run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics #check for syntax errors
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics  #run all the available checks on the service folder of your repository

      name: Run unit test with nose
      run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
